#!/usr/bin/env bash
# Regenerate config.yaml from the models GitHub Copilot currently exposes.
#
# Routing rules (per-model, from the API's supported_endpoints field):
#   claude-*                          -> anthropic/<id> @ http://localhost:4141 (copilot-api relays
#                                        to Copilot's NATIVE Anthropic /v1/messages: thinking works.
#                                        NOT litellm's github_copilot native path — its
#                                        copilot-integration-id is rejected: "unknown Copilot-Integration-Id")
#   supports "/responses"             -> anthropic/<id> @ http://localhost:4141 (copilot-api
#                                        translates Anthropic messages -> Copilot /responses;
#                                        needed for gpt-5.x/codex/grok which reject /chat/completions)
#   everything else (chat)            -> github_copilot/<id>   (/chat/completions, direct from litellm)
# Plus: a "claude-<id>" alias for every non-claude model, because Claude Code's
# /model gateway discovery only lists ids starting with claude/anthropic.
#
# Fail-closed: never overwrites config.yaml unless a plausible model list was fetched.
# Re-run whenever Copilot ships new models, then: ~/litellm-copilot/restart-proxy.sh
set -euo pipefail

DIR="$HOME/litellm-copilot"
CFG="$DIR/config.yaml"
CRED="$HOME/.config/litellm/github_copilot"

# --- 1. Mint a fresh short-lived Copilot bearer from the long-lived OAuth token ---
GH_TOKEN=$(cat "$CRED/access-token")
BEARER=$(curl -fsS --max-time 20 https://api.github.com/copilot_internal/v2/token \
  -H "Authorization: token $GH_TOKEN" \
  -H "editor-version: vscode/1.100.0" | jq -re '.token')

# --- 2. Fetch the live model catalog ---
MODELS_JSON=$(curl -fsS --max-time 20 https://api.githubcopilot.com/models \
  -H "Authorization: Bearer $BEARER" \
  -H "Copilot-Integration-Id: vscode-chat" \
  -H "editor-version: vscode/1.100.0")

COUNT=$(jq -r '[.data[] | select((.capabilities.type // "")=="chat")] | length' <<<"$MODELS_JSON")
if [ -z "$COUNT" ] || [ "$COUNT" -lt 5 ]; then
  echo "ERROR: only $COUNT chat models returned — refusing to overwrite $CFG" >&2
  exit 1
fi

# --- 3. Generate config to a temp file, then atomically replace ---
TMP=$(mktemp "$DIR/.config.yaml.XXXXXX")
trap 'rm -f "$TMP"' EXIT

emit_headers() {
  echo "      extra_headers:"
  echo '        editor-version: "vscode/1.100.0"'
  echo '        Copilot-Integration-Id: "vscode-chat"'
}

emit_entry() { # $1=model_name  $2=route(copilot|copilot-bare|capi)  $3=upstream id
  local name="$1" route="$2" id="$3"
  printf '  - model_name: "%s"\n' "$name"
  echo   "    litellm_params:"
  if [ "$route" = "capi" ]; then
    printf '      model: anthropic/%s\n' "$id"
    echo   "      api_base: http://localhost:4141"
    echo   "      api_key: dummy"
  else
    printf '      model: github_copilot/%s\n' "$id"
    # claude-*: NO extra_headers — litellm's native Anthropic /v1/messages passthrough
    # injects its own; overriding Copilot-Integration-Id breaks it ("unknown Copilot-Integration-Id")
    [ "$route" = "copilot" ] && emit_headers
  fi
}

{
  echo "# AUTO-GENERATED by refresh-models.sh $(date '+%Y-%m-%d %H:%M') — do not edit by hand."
  echo "# claude-* -> Copilot native Anthropic; /responses-only -> copilot-api :4141; rest -> chat/completions."
  echo "model_list:"

  # skip: non-chat (embeddings), internal compaction model, and the broken bare alias
  while IFS=$'\t' read -r id endpoints; do
    [ -z "$id" ] && continue
    case "$id" in trajectory-compaction|mai-code-1-flash) continue ;; esac

    if [[ "$id" == claude-* ]]; then
      emit_entry "$id" capi "$id"
    elif [[ ",$endpoints," == *",/responses,"* ]] || [[ ",$endpoints," == *",ws:/responses,"* ]]; then
      emit_entry "$id" capi "$id"
      emit_entry "claude-$id" capi "$id"          # picker-visible alias
    else
      emit_entry "$id" copilot "$id"
      emit_entry "claude-$id" copilot "$id"       # picker-visible alias
    fi
  done < <(jq -r '.data[] | select((.capabilities.type // "")=="chat")
                  | [.id, ((.supported_endpoints // []) | join(","))] | @tsv' <<<"$MODELS_JSON" | sort)

  # Compat aliases: real Anthropic model ids Claude Code may request (saved defaults,
  # alias resolution) mapped to the nearest Copilot model. Without these, unknown
  # claude-* names fall into the wildcard -> litellm's broken native path -> 400.
  emit_entry "claude-fable-5"            capi    "claude-opus-5"
  emit_entry "claude-opus-4-5"           capi    "claude-opus-4.6"
  emit_entry "claude-opus-4-1"           capi    "claude-opus-4.6"
  emit_entry "claude-sonnet-4-5"         capi    "claude-sonnet-4.6"
  emit_entry "claude-sonnet-4-6"         capi    "claude-sonnet-4.6"
  emit_entry "claude-haiku-4-5"          copilot "gpt-4o-mini"
  emit_entry "claude-3-5-haiku-20241022" copilot "gpt-4o-mini"

  # wildcard fallback: any unknown name -> plain Copilot chat route
  echo '  - model_name: "*"'
  echo "    litellm_params:"
  echo "      model: github_copilot/*"
  emit_headers
  echo
  echo "litellm_settings:"
  echo "  drop_params: true      # Copilot chat/completions rejects params like 'thinking'"
  echo
  echo "general_settings:"
  echo "  master_key: os.environ/LITELLM_MASTER_KEY"
} > "$TMP"

[ -f "$CFG" ] && cp "$CFG" "$CFG.bak"
mv "$TMP" "$CFG"
trap - EXIT
echo "Wrote $CFG ($COUNT chat models; previous saved as config.yaml.bak)."
echo "Apply with: ~/litellm-copilot/restart-proxy.sh"
