"""Build one-to-one gateway catalogs from Copilot's user-visible models.

Two LiteLLM configs come from the same validated catalog:

* Claude Code (``config.yaml``): public names are ``claude-<id>`` so Claude
  Code's model picker accepts every Copilot model; native Claude and
  Responses-only models go through copilot-api's Anthropic endpoint.
* Codex (``config-codex.yaml``): public names are the plain Copilot ids and
  requests use the OpenAI Responses API, so Responses models are proxied
  natively to copilot-api's ``/v1/responses``.

Output is JSON (also valid YAML). Only same-model spellings become hidden
aliases; a named model never resolves to a different model.
"""
from __future__ import annotations

import json
import re
import urllib.error
import urllib.request

HEADERS = {"editor-version": "vscode/1.100.0", "Copilot-Integration-Id": "vscode-chat"}
TOKEN_URL = "https://api.github.com/copilot_internal/v2/token"
MODELS_URL = "https://api.githubcopilot.com/models"
HEADER = "# AUTO-GENERATED by `ccgw refresh` — do not edit by hand."
RESPONSES = ("/responses", "ws:/responses")
# Codex sends these Responses tool types; Copilot's xAI models reject them.
XAI_UNSUPPORTED_TOOL_TYPES = ("namespace", "web_search")
CODEX_CALLBACK = "copilot_gateway.hooks.tool_filter"


class CatalogError(ValueError):
    pass


def token_label(value):
    if value is None:
        return "미제공"
    if value % 1000000 == 0:
        return f"{value // 1000000}M"
    if value % 1000 == 0:
        return f"{value // 1000}K"
    return f"{value:,}"


def token_limit(limits, key, required=False):
    value = limits.get(key)
    if required and value is None:
        raise CatalogError(f"missing {key}; cannot use another provider's limit")
    if value is not None and (type(value) is not int or value <= 0):
        raise CatalogError(f"invalid {key}: expected a positive integer")
    return value


def select_models(catalog):
    rows = catalog.get("data") if isinstance(catalog, dict) else None
    if not isinstance(rows, list) or not all(isinstance(row, dict) for row in rows):
        raise CatalogError("invalid Copilot catalog: expected data array")
    chat = [row for row in rows if (row.get("capabilities") or {}).get("type") == "chat"]
    if len(chat) < 5:
        raise CatalogError(f"only {len(chat)} chat models returned; refusing to replace config")

    selected, seen = [], set()
    for row in chat:
        if row.get("model_picker_enabled") is not True:
            continue
        model_id, name = row.get("id"), row.get("name")
        if not isinstance(model_id, str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", model_id):
            raise CatalogError("invalid Copilot model id")
        if not isinstance(name, str) or not name.strip():
            raise CatalogError(f"missing display name for {model_id}")
        if model_id in seen:
            raise CatalogError(f"duplicate Copilot model id: {model_id}")
        seen.add(model_id)
        if re.search(r"internal[\s_-]*only", name, re.IGNORECASE):
            continue
        policy = row.get("policy")
        if policy is None:
            policy = {}
        if not isinstance(policy, dict):
            raise CatalogError(f"invalid policy for {model_id}")
        if policy.get("state") not in (None, "enabled"):
            continue
        endpoints = row.get("supported_endpoints") or []
        if not isinstance(endpoints, list):
            raise CatalogError(f"invalid supported_endpoints for {model_id}")
        limits = row["capabilities"].get("limits")
        if not isinstance(limits, dict):
            raise CatalogError(f"invalid limits for {model_id}")
        selected.append({
            "id": model_id, "name": " ".join(name.split()), "vendor": row.get("vendor"),
            "preview": row.get("preview") is True, "endpoints": endpoints,
            "context": token_limit(limits, "max_context_window_tokens", required=True),
            "prompt": token_limit(limits, "max_prompt_tokens", required=True),
            "output": token_limit(limits, "max_output_tokens", required=True),
            "non_streaming": token_limit(limits, "max_non_streaming_output_tokens"),
        })
    if not selected:
        raise CatalogError("no user-visible, policy-enabled models; refusing to replace config")
    return sorted(selected, key=lambda item: item["id"])


def model_info(row):
    description = (f"Copilot · 컨텍스트 {token_label(row['context'])} · 입력 {token_label(row['prompt'])}"
                   f" · 출력 {token_label(row['output'])}")
    if row["non_streaming"] is not None:
        description += f" · 비스트림 {token_label(row['non_streaming'])}"
    if row["preview"]:
        description += " · Preview"
    info = {
        "mode": "chat", "display_name": row["name"], "description": description,
        "gateway_provider": "github_copilot", "upstream_model_id": row["id"],
        "upstream_vendor": row["vendor"],
    }
    for key, value in (("max_context_window_tokens", row["context"]), ("max_input_tokens", row["prompt"]),
                       ("max_output_tokens", row["output"]),
                       ("max_non_streaming_output_tokens", row["non_streaming"])):
        if value is not None:
            info[key] = value
    return info


def _assemble(rows, public_name, params_for, extra_spellings, extra_info=lambda row: {}):
    entries, aliases = [], {}
    public_names = {public_name(row["id"]) for row in rows}
    if len(public_names) != len(rows):
        raise CatalogError("Copilot ids collide with gateway model names")

    def add_alias(alias, target):
        if alias == target:
            return
        if alias in public_names or (alias in aliases and aliases[alias]["model"] != target):
            raise CatalogError(f"ambiguous model alias: {alias}")
        aliases[alias] = {"model": target, "hidden": True}

    for row in rows:
        public_id = public_name(row["id"])
        entries.append({"model_name": public_id, "litellm_params": params_for(row),
                        "model_info": {**model_info(row), **extra_info(row)}})
        for spelling in sorted(extra_spellings(row, public_id)):
            add_alias(spelling, public_id)
    return {
        "model_list": entries,
        "router_settings": {"model_group_alias": aliases},
        "litellm_settings": {"drop_params": True},
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }


def claude_name(model_id):
    return model_id if model_id.startswith("claude-") else f"claude-{model_id}"


def build_config(catalog, capi_base="http://127.0.0.1:4141"):
    """LiteLLM config for Claude Code (Anthropic Messages clients)."""
    def params_for(row):
        model_id, endpoints = row["id"], row["endpoints"]
        # Legacy small/fast requests also need the hosted WebSearch translator.
        if ((model_id.startswith("claude-") and "/v1/messages" in endpoints)
                or (model_id == "gpt-4o-mini" and "/chat/completions" in endpoints)
                or any(endpoint in endpoints for endpoint in RESPONSES)):
            return {"model": f"anthropic/{model_id}", "api_base": capi_base, "api_key": "dummy"}
        if "/chat/completions" in endpoints:
            return {"model": f"github_copilot/{model_id}", "extra_headers": HEADERS.copy()}
        raise CatalogError(f"no supported gateway endpoint for {model_id}")

    def spellings(row, public_id):
        values = {row["id"], public_id}
        if row["id"].startswith("claude-"):
            values.add(row["id"].replace(".", "-"))
        if row["context"] >= 1000000:
            values |= {f"{value}[1m]" for value in values}
        return values

    return _assemble(select_models(catalog), claude_name, params_for, spellings)


def build_codex_config(catalog, capi_base="http://127.0.0.1:4141"):
    """LiteLLM config for Codex (OpenAI Responses clients)."""
    def params_for(row):
        model_id, endpoints = row["id"], row["endpoints"]
        if model_id.startswith("claude-") and "/v1/messages" in endpoints:
            return {"model": f"anthropic/{model_id}", "api_base": capi_base, "api_key": "dummy"}
        if any(endpoint in endpoints for endpoint in RESPONSES):
            return {"model": f"openai/{model_id}", "api_base": f"{capi_base}/v1", "api_key": "dummy"}
        if "/chat/completions" in endpoints:
            return {"model": f"github_copilot/{model_id}", "extra_headers": HEADERS.copy()}
        raise CatalogError(f"no supported gateway endpoint for {model_id}")

    def spellings(row, public_id):
        return {row["id"].replace(".", "-")} if row["id"].startswith("claude-") else set()

    def extra_info(row):
        # Copilot /responses for xAI returns 400/422 on these Codex tool types.
        if row["vendor"] == "xAI" and any(endpoint in row["endpoints"] for endpoint in RESPONSES):
            return {"unsupported_tool_types": list(XAI_UNSUPPORTED_TOOL_TYPES)}
        return {}

    config = _assemble(select_models(catalog), lambda model_id: model_id, params_for, spellings, extra_info)
    config["litellm_settings"]["callbacks"] = [CODEX_CALLBACK]
    return config


def render(config) -> str:
    return HEADER + "\n" + json.dumps(config, ensure_ascii=False, indent=2) + "\n"


def parse_rendered(text: str):
    first, _, body = text.partition("\n")
    if not first.startswith("#"):
        body = text
    return json.loads(body)


def format_models(config) -> str:
    lines = ["Model\tCopilot ID\tContext\tInput\tOutput\tNon-stream output"]
    for row in config["model_list"]:
        info = row["model_info"]
        values = [info["display_name"], info["upstream_model_id"]]
        values.extend(token_label(info.get(key)) for key in (
            "max_context_window_tokens", "max_input_tokens", "max_output_tokens", "max_non_streaming_output_tokens",
        ))
        lines.append("\t".join(values))
    return "\n".join(lines)


def _get_json(url, headers, timeout=20):
    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        raise CatalogError(f"{url} returned HTTP {error.code}") from None
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise CatalogError(f"cannot reach {url}: {getattr(error, 'reason', error)}") from None
    except (UnicodeError, json.JSONDecodeError):
        raise CatalogError(f"{url} returned invalid JSON") from None


def fetch_catalog(token_dir):
    """Mint a short-lived bearer and fetch the live catalog (credentials never logged)."""
    try:
        github_token = (token_dir / "access-token").read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        raise CatalogError(f"no GitHub Copilot login at {token_dir}; run `ccgw login`") from None
    if not github_token:
        raise CatalogError(f"empty GitHub Copilot token at {token_dir}; run `ccgw login`")
    bearer = _get_json(TOKEN_URL, {"Authorization": f"token {github_token}",
                                   "editor-version": HEADERS["editor-version"]}).get("token")
    if not isinstance(bearer, str) or not bearer:
        raise CatalogError("Copilot token endpoint returned no token")
    return _get_json(MODELS_URL, {"Authorization": f"Bearer {bearer}", **HEADERS})
